### ISSUE TITLE
Policy Recipe - Constant Restart

### ISSUE THREAD

**Issue by bdwyertech** [rabbitmq/chef-cookbook#441] opened 2017-05-11 08:55 UTC
The policy recipe causes a restart on every Chef run because the policy resource doesn't use a guard on the `:set` action, this must be something new.  Quick glance shows the `:clear` action uses a guard but set doesn't, so maybe this restart notification should just be stripped out, thats what I did. Idk.

https://github.com/rabbitmq/chef-cookbook/blob/master/recipes/policy_management.rb#L33

**Comment by michaelklishin** [comment] 2017-05-11 10:12
@bdwyertech sounds like a duplicate of #424? Let me know if I'm wrong.

**Comment by michaelklishin** [comment] 2017-05-11 10:12
Actually, since you are linking to master I probably am.

**Comment by bdwyertech** [comment] 2017-05-11 12:37
Hey @michaelklishin, thanks for the really fast response!

To clarify, this is on latest Supermarket release. Anyway, filed that at the end of a 3 hour maint window, need to get some sleep. I'll take a look later, need to do some more reading about expected behavior.

**Comment by michaelklishin** [comment] 2018-02-19 13:49
Addressed in #445.

**Closed by michaelklishin** 2018-02-19 13:49 UTC
Labels: Waiting for Contributor Response
