### ISSUE TITLE
Using Debian 16.04 Rabbit 3.7.3  fails to download - 404

### ISSUE THREAD

**Issue by wjdavis5** [rabbitmq/chef-cookbook#481] opened 2018-02-14 21:17 UTC
Using the latest cookbook and Ubuntu 16.04

Steps to reproduce:

set : 

`['rabbitmq']['version'] = '3.7.3'`

Then run
`rabbitmq::default`

Expected Result - Installs Rabbit 3.7.3

Actual result - below.

```
==> default: Recipe: rabbitmq::default
==> default:   * dpkg_autostart[rabbitmq-server] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb] action create_if_missing
==> default: [2018-02-14T13:14:06-08:00] WARN: remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb] cannot be downloaded from https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_7_3/rabbitmq-server_3.7.3-1_all.deb: 404 "Not Found"
==> default: [2018-02-14T13:14:06-08:00] WARN: remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb] cannot be downloaded from https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_7_3/rabbitmq-server_3.7.3-1_all.deb: 404 "Not Found"
==> default:
==> default:
==> default:     ================================================================================
==> default:     Error executing action `create_if_missing` on resource 'remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb]'
==> default:
==> default: ================================================================================
==> default:
==> default:     Net::HTTPServerException
==> default:     ------------------------
==> default:
==> default: 404 "Not Found"
==> default:
==> default:     Resource Declaration:
==> default:
==> default: ---------------------
==> default:     # In /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb
==> default:
==> default:      87:     remote_file "#{Chef::Config[:file_cache_path]}/#{deb_package_name}" do
==> default:      88:       source "#{deb_package_url}#{deb_package_name}"
==> default:      89:       action :create_if_missing
==> default:      90:     end
==> default:
==> default:  91:     dpkg_package 'rabbitmq-server' do
==> default:
==> default:     Compiled Resource:
==> default:
==> default: ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/rabbitmq/recipes/default.rb:87:in `from_file'
==> default:
==> default:     remote_file("/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb") do
==> default:       provider Chef::Provider::RemoteFile
==> default:       action [:create_if_missing]
==> default:       default_guard_interpreter :default
==> default:       source ["https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_7_3/rabbitmq-server_3.7.3-1_all.deb"]
==> default:       use_etag true
==> default:       use_last_modified true
==> default:       declared_type :remote_file
==> default:       cookbook_name "rabbitmq"
==> default:       recipe_name "default"
==> default:       remote_domain nil
==> default:       remote_user nil
==> default:       owner nil
==> default:       group nil
==> default:       checksum nil
==> default:       mode nil
==> default:
==> default:   verifications []
==> default:     end
==> default:
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=13.7.16
==> default:     platform=ubuntu
==> default:     platform_version=16.04
==> default:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
==> default:     program_name=chef-solo worker: ppid=4123;start=13:13:21;
==> default:     executable=/opt/chef/bin/chef-solo
==> default:
==> default: [2018-02-14T13:14:06-08:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2018-02-14T13:14:06-08:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2018-02-14T13:14:06-08:00] ERROR: Running exception handlers
==> default: [2018-02-14T13:14:06-08:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2018-02-14T13:14:06-08:00] ERROR: Exception handlers complete
==> default: [2018-02-14T13:14:06-08:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 8 resources updated in 45 seconds
==> default: [2018-02-14T13:14:06-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-02-14T13:14:06-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-02-14T13:14:06-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-02-14T13:14:06-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-02-14T13:14:06-08:00] ERROR: remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb] (rabbitmq::default line 87) had an error: Net::HTTPServerException: 404 "Not Found"
==> default: [2018-02-14T13:14:06-08:00] ERROR: remote_file[/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb] (rabbitmq::default line 87) had an error: Net::HTTPServerException: 404 "Not Found"
==> default: [2018-02-14T13:14:06-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
==> default: [2018-02-14T13:14:06-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by michaelklishin** [comment] 2018-02-14 21:20
Consider providing more than a single node attribute when reporting issues. More than the version can be important.

Duplicate of #479, addressed in master and [documented](https://github.com/rabbitmq/chef-cookbook#supported-rabbitmq-versions).

**Closed by michaelklishin** 2018-02-14 21:20 UTC

**Comment by wjdavis5** [comment] 2018-02-14 21:33
Ok. Here is all the information you need.

Create the below vagrantfile and then

`vagrant up`
`vagrant provision`

and then see the final output of it failing to download and install the software.

I have read the issue you linked, as well as the documentation you linked. So you're saying that I need to also override the download url and download file name? If this is addressed in master is there a specific commit I can refer to find the proper values to set those items? I'll go browse the master branch.


**VAGRANTFILE**
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
  config.vm.box_version = "1.3.30"
  #config.vm.provision "shell", inline: "touch /etc/is_vagrant_vm"
  #config.vm.provision "shell", inline: "adduser --add_extra_groups ubuntu --disabled-password -q --system --group"
  #config.vm.provision "shell", inline: "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' | sudo tee --append /etc/sudoers"
  
  
  config.vm.provision "chef_solo" do |chef|
    chef.node_name = "foo"
    chef.add_recipe "rabbitmq::default"
    chef.json = {
      "rabbitmq" => {
        "version" => "3.7.3"
      }
    }
  end
end
```

**Comment by wjdavis5** [comment] 2018-02-14 21:39
For others to reference, here is the commit he refers too that will eventually be released:

https://github.com/rabbitmq/chef-cookbook/commit/7009e24f8343b86a9bdaa275e94cdbf8c1290db7
#

**Comment by michaelklishin** [comment] 2018-02-14 21:42
[5.5.0 is out](https://github.com/rabbitmq/chef-cookbook/commit/fdfbcf39015458c3f2f4a82a2d4730a730e13fea) and includes that commit. I'm trying to reproduce with it.

**Comment by wjdavis5** [comment] 2018-02-14 21:46
Ok, thank you for pushing that so quickly, if you just tried to recreate with the vagrant I specified I'm sure you've already seen this:

`STDERR: dpkg-deb: error: '/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb' is not a debian format archive`

**Comment by michaelklishin** [comment] 2018-02-14 22:10
I have not seen that. I'm currently fighting my Vagrant setup but both our CI and my manual attempts at installing the 3.7.3 package from Bintray succeed.

**Comment by michaelklishin** [comment] 2018-02-14 22:19
I have the following `Cheffile` for Librarian:

``` ruby
site "https://supermarket.getchef.com/api/v1"

cookbook "rabbitmq"
```

and used it to install the cookbook + dependencies to `$HOME/temp/cookbooks`.

With the following Vagrantfile:

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision "chef_solo" do |chef|
    # chef.provisioning_path = "/tmp/vagrant-chef-123/chef-solo"
    chef.cookbooks_path = "#{ENV['HOME']}/temp/cookbooks"

    chef.add_recipe "rabbitmq::default"
    chef.json = {
      "rabbitmq" => {
        "version" => "3.7.3"
      }
    }
  end
end
```

I am getting

```
==> default: STDERR: dpkg: dependency problems prevent configuration of rabbitmq-server:
==> default:  rabbitmq-server depends on erlang-nox (>= 1:19.3) | esl-erlang (>= 1:19.3); however:
==> default:   Version of erlang-nox on system is 1:18.3-dfsg-1ubuntu3.1.
==> default:   Package esl-erlang is not installed.
==> default:
==> default: dpkg: error processing package rabbitmq-server (--install):
==> default:  dependency problems - leaving unconfigured
==> default: Errors were encountered while processing:
==> default:  rabbitmq-server
==> default: ---- End output of ["dpkg", "-i", "/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb"] ----
==> default: Ran ["dpkg", "-i", "/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb"] returned 1
==> default: [2018-02-14T22:17:23+00:00] ERROR: dpkg_package[rabbitmq-server] (rabbitmq::default line 97) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of ["dpkg", "-i", "/var/chef/cache/rabbitmq-server_3.7.3-1_all.deb"] ----
==> default: STDOUT: Selecting previously unselected package rabbitmq-server.
==> default: (Reading database ... 54977 files and directories currently installed.)
==> default: Preparing to unpack .../rabbitmq-server_3.7.3-1_all.deb ...
==> default: Unpacking rabbitmq-server (3.7.3-1) ...
==> default: Processing triggers for man-db (2.7.5-1) ...
==> default: Processing triggers for systemd (229-4ubuntu21) ...
==> default: Processing triggers for ureadahead (0.100.0-19) ...
==> default: STDERR: dpkg: dependency problems prevent configuration of rabbitmq-server:
==> default:  rabbitmq-server depends on erlang-nox (>= 1:19.3) | esl-erlang (>= 1:19.3); however:
==> default:   Version of erlang-nox on system is 1:18.3-dfsg-1ubuntu3.1.
==> default:   Package esl-erlang is not installed.
==> default:
==> default: dpkg: error processing package rabbitmq-server (--install):
==> default:  dependency problems - leaving unconfigured
==> default: Errors were encountered while processing:
==> default:  rabbitmq-server
```

which is merely an indication of the fact that Ubuntu 16.04 does not provide Erlang 19.3 and the `erlang` cookbook uses the `package` method by default.

**Comment by michaelklishin** [comment] 2018-02-14 22:35
Now if I update my Vagrantfile to force Erlang installation from the ESL repo like so:

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provision "chef_solo" do |chef|
    # chef.provisioning_path = "/tmp/vagrant-chef-123/chef-solo"
    chef.cookbooks_path = "#{ENV['HOME']}/temp/cookbooks"

    chef.add_recipe "erlang::default"
    chef.add_recipe "rabbitmq::default"

    chef.json = {
      "erlang" => {
        "install_method": "esl"
      },
      "rabbitmq" => {
        "version" => "3.7.3"
      }
    }
  end
end

```

and remove `erlang-nox` 18.3 from the system, both Erlang 20.2.x and RabbitMQ 3.7.3 provision successfully with `vagrant provision`. I can `vagrant ssh` and use CLI tools and so on.
